name: Emerald
version: '${project.version}'
main: fr.fowled.emerald.Emerald
api-version: 1.19
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.12.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.12.0